apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-sync-api
  #namespace: bagarote-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-sync-api
  template:
    metadata:
      labels:
        app: db-sync-api
    spec:
#      securityContext:
#        runAsUser: 5000
#        runAsGroup: 5000
      containers:
      - name: db-sync-api
        image: registry.bagarote.dev.br/bagarote/db-sync-api:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: NotIn
                values:
                - ks01
---
apiVersion: v1
kind: Service
metadata:
  name: db-sync-api-service
  #namespace: bagarote-prod
spec:
  selector:
    app: db-sync-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
