FROM php:8.3.9-cli-alpine3.20

RUN apk update && apk upgrade --no-cache
RUN apk add curl zip unzip vim lynx git postgresql-client --no-cache
RUN docker-php-ext-install bcmath pdo opcache pcntl

RUN ln -s /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
COPY /php/extra.ini /usr/local/etc/php/conf.d/99_extra.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /usr/local/bin/app
COPY . ./
COPY .env.example .env

RUN composer update --no-dev

RUN php artisan key:generate

EXPOSE 8000

CMD [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000" ]
